function W = cvuKltRead(format, sFrame, eFrame)
% cvuKltRead - Read KLT feature data generated by [4]
%
% Synopsis
%  W = cvuKltRead(format, sFrame, eFrame)
%
% Inputs ([]s are optional)
%  (string) format  a filename format which has one %d.
%                   See more sprintf
%  (int)    sFrame  the start frame number
%  (int)    eFrame  the end frame number
%
% Outputs ([]s are optional)
%  (matrix) W        2F x P measurement matrix (Section 3) [1]
%
% Examples
%  W = cvuKltRead('image/hotel/hotel.seq%d.feat.txt', 0, 100);
%
% References
%  [1] C. Tomasi and T. Kanade, "Shape and motion from image streams
%  -- a factorization method,"   International Journal of Computer
%  Vision, 9(2):137--154, 1992.
%  [4] KLT: An Implementation of the Kanade-Lucas-Tomasi Feature Tracker
%  http://www.ces.clemson.edu/~stb/klt/
%
% Authors
%  Naotoshi Seo <sonots(at)sonots.com>
%
% License
%  The program is free to use for non-commercial academic purposes,
%  but for course works, you must understand what is going inside to use.
%  The program can be used, modified, or re-distributed for any purposes
%  if you or one of your group understand codes (the one must come to
%  court if court cases occur.) Please contact the authors if you are
%  interested in using the program without meeting the above conditions.

% Changes
%  11/01/2006  First Edition
for i = sFrame:eFrame
    W(i+1, :, :) = load(sprintf(format, i));
end
U = W(:, :, 1);
V = W(:, :, 2);
W = [U ; V];
W = round(W);
% Delete errored tracking points (whose value -1)
W = W(:, sum(W < 0, 1) == 0);
end
