Description of aconv
Home > WaveUtilities > aconv.m
aconv
PURPOSE
aconv -- Convolution Tool for Two-Scale Transform
SYNOPSIS
function y = aconv(f,x)
DESCRIPTION
 aconv -- Convolution Tool for Two-Scale Transform
  Usage
    y = aconv(f,x)
  Inputs
    f    filter
    x    1-d signal
  Outputs
    y    filtered result
  Description
    Filtering by periodic convolution of x with the
    time-reverse of f.
  See Also
    iconv, UpDyadHi, UpDyadLo, DownDyadHi, DownDyadLo
CROSS-REFERENCE INFORMATION
This function calls:
Reverse reverse -- Reverse order of elements in 1-d signal
This function is called by:
DownDyadLo DownDyadLo -- Lo-Pass Downsampling operator (periodized)
UpDyadHi UpDyadHi -- Hi-Pass Upsampling operator; periodized