Description of DownDyadLo
Home > WaveUtilities > DownDyadLo.m
DownDyadLo
PURPOSE
DownDyadLo -- Lo-Pass Downsampling operator (periodized)
SYNOPSIS
function d = DownDyadLo(x,qmf)
DESCRIPTION
 DownDyadLo -- Lo-Pass Downsampling operator (periodized)
  Usage
    d = DownDyadLo(x,f)
  Inputs
    x    1-d signal at fine scale
    f    filter
  Outputs
    y    1-d signal at coarse scale
  See Also
    DownDyadHi, UpDyadHi, UpDyadLo, FWT_PO, aconv
CROSS-REFERENCE INFORMATION
This function calls:
aconv aconv -- Convolution Tool for Two-Scale Transform
This function is called by:
FWT2_PO FWT2_PO -- 2-d MRA wavelet transform (periodized, orthogonal)
FWT_PO FWT_PO -- Forward Wavelet Transform (periodized, orthogonal)