Description of DownDyadHi
Home > WaveUtilities > DownDyadHi.m
DownDyadHi
PURPOSE
DownDyadHi -- Hi-Pass Downsampling operator (periodized)
SYNOPSIS
function d = DownDyadHi(x,qmf)
DESCRIPTION
 DownDyadHi -- Hi-Pass Downsampling operator (periodized)
  Usage
    d = DownDyadHi(x,f)
  Inputs
    x    1-d signal at fine scale
    f    filter
  Outputs
    y    1-d signal at coarse scale
  See Also
    DownDyadLo, UpDyadHi, UpDyadLo, FWT_PO, iconv
CROSS-REFERENCE INFORMATION
This function calls:
MirrorFilt MirrorFilt -- Apply (-1)^t modulation
iconv iconv -- Convolution Tool for Two-Scale Transform
lshift lshift -- Circular left shift of 1-d signal
This function is called by:
FWT2_PO FWT2_PO -- 2-d MRA wavelet transform (periodized, orthogonal)
FWT_PO FWT_PO -- Forward Wavelet Transform (periodized, orthogonal)