Description of FWT_PO
Home > WaveUtilities > FWT_PO.m
FWT_PO
PURPOSE
FWT_PO -- Forward Wavelet Transform (periodized, orthogonal)
SYNOPSIS
function wcoef = FWT_PO(x,L,qmf)
DESCRIPTION
 FWT_PO -- Forward Wavelet Transform (periodized, orthogonal)
  Usage
    wc = FWT_PO(x,L,qmf)
  Inputs
    x    1-d signal; length(x) = 2^J
    L    Coarsest Level of V_0;  L << J
    qmf  quadrature mirror filter (orthonormal)
  Outputs
    wc    1-d wavelet transform of x.
  Description
    1. qmf filter may be obtained from MakeONFilter
    2. usually, length(qmf) < 2^(L+1)
    3. To reconstruct use IWT_PO
  See Also
    IWT_PO, MakeONFilter
CROSS-REFERENCE INFORMATION
This function calls:
DownDyadHi DownDyadHi -- Hi-Pass Downsampling operator (periodized)
DownDyadLo DownDyadLo -- Lo-Pass Downsampling operator (periodized)
ShapeAsRow ShapeAsRow -- Make signal a row vector
ShapeLike ShapeLike -- Make 1-d signal with given shape
dyad dyad -- Index entire j-th dyad of 1-d wavelet xform
dyadlength dyadlength -- Find length and dyadic length of array
This function is called by:
WaveletTransform WAVELETTRANSFORM 1D wavelet transform