Description of IWT_PO
Home > WaveUtilities > IWT_PO.m
IWT_PO
PURPOSE
IWT_PO -- Inverse Wavelet Transform (periodized, orthogonal)
SYNOPSIS
function x = IWT_PO(wc,L,qmf)
DESCRIPTION
 IWT_PO -- Inverse Wavelet Transform (periodized, orthogonal)
  Usage
    x = IWT_PO(wc,L,qmf)
  Inputs
    wc     1-d wavelet transform: length(wc) = 2^J.
    L      Coarsest scale (2^(-L) = scale of V_0); L << J;
    qmf    quadrature mirror filter
  Outputs
    x      1-d signal reconstructed from wc
  Description
    Suppose wc = FWT_PO(x,L,qmf) where qmf is an orthonormal quad. mirror
    filter, e.g. one made by MakeONFilter. Then x can be reconstructed by
      x = IWT_PO(wc,L,qmf)
  See Also
    FWT_PO, MakeONFilter
CROSS-REFERENCE INFORMATION
This function calls:
ShapeAsRow ShapeAsRow -- Make signal a row vector
ShapeLike ShapeLike -- Make 1-d signal with given shape
UpDyadHi UpDyadHi -- Hi-Pass Upsampling operator; periodized
UpDyadLo UpDyadLo -- Lo-Pass Upsampling operator; periodized
dyad dyad -- Index entire j-th dyad of 1-d wavelet xform
dyadlength dyadlength -- Find length and dyadic length of array
This function is called by:
IWaveletTransform WAVELETTRANSFORM 1D inverse wavelet transform