Description of MakeONFilter
Home > WaveUtilities > MakeONFilter.m
MakeONFilter
PURPOSE
MakeONFilter -- Generate Orthonormal QMF Filter for Wavelet Transform
SYNOPSIS
function f = MakeONFilter(Type,Par)
DESCRIPTION
 MakeONFilter -- Generate Orthonormal QMF Filter for Wavelet Transform
  Usage
    qmf = MakeONFilter(Type,Par)
  Inputs
    Type   string, 'Haar', 'Beylkin', 'Coiflet', 'Daubechies',
           'Symmlet', 'Vaidyanathan','Battle'
    Par    integer, it is a parameter related to the support and vanishing
           moments of the wavelets, explained below for each wavelet.
 Outputs
    qmf    quadrature mirror filter
  Description
    The Haar filter (which could be considered a Daubechies-2) was the
    first wavelet, though not called as such, and is discontinuous.
    The Beylkin filter places roots for the frequency response function
    close to the Nyquist frequency on the real axis.
    The Coiflet filters are designed to give both the mother and father
    wavelets 2*Par vanishing moments; here Par may be one of 1,2,3,4 or 5.
    The Daubechies filters are minimal phase filters that generate wavelets
    which have a minimal support for a given number of vanishing moments.
    They are indexed by their length, Par, which may be one of
    4,6,8,10,12,14,16,18 or 20. The number of vanishing moments is par/2.
    Symmlets are also wavelets within a minimum size support for a given
    number of vanishing moments, but they are as symmetrical as possible,
    as opposed to the Daubechies filters which are highly asymmetrical.
    They are indexed by Par, which specifies the number of vanishing
    moments and is equal to half the size of the support. It ranges
    from 4 to 10.
    The Vaidyanathan filter gives an exact reconstruction, but does not
    satisfy any moment condition.  The filter has been optimized for
    speech coding.
    The Battle-Lemarie filter generate spline orthogonal wavelet basis.
    The parameter Par gives the degree of the spline. The number of
    vanishing moments is Par+1.
  See Also
    FWT_PO, IWT_PO, FWT2_PO, IWT2_PO, WPAnalysis
  References
    The books by Daubechies and Wickerhauser.
CROSS-REFERENCE INFORMATION
This function calls:
reverse reverse -- Reverse order of elements in 1-d signal
This function is called by:
IWaveletTransform WAVELETTRANSFORM 1D inverse wavelet transform
IWaveletTransform2D WAVELETTRANSFORM 2D inverse wavelet transform
WaveletTransform WAVELETTRANSFORM 1D wavelet transform
WaveletTransform2D WAVELETTRANSFORM 2D wavelet transform