Description of UpDyadLo
Home > WaveUtilities > UpDyadLo.m
UpDyadLo
PURPOSE
UpDyadLo -- Lo-Pass Upsampling operator; periodized
SYNOPSIS
function y = UpDyadLo(x,qmf)
DESCRIPTION
 UpDyadLo -- Lo-Pass Upsampling operator; periodized
  Usage
    u = UpDyadLo(d,f)
  Inputs
    d    1-d signal at coarser scale
    f    filter
  Outputs
    u    1-d signal at finer scale
  See Also
    DownDyadLo, DownDyadHi, UpDyadHi, IWT_PO, iconv
CROSS-REFERENCE INFORMATION
This function calls:
UpSample UpSample -- Upsampling operator
iconv iconv -- Convolution Tool for Two-Scale Transform
This function is called by:
IWT2_PO IWT2_PO -- Inverse 2-d MRA wavelet transform (periodized, orthogonal)
IWT_PO IWT_PO -- Inverse Wavelet Transform (periodized, orthogonal)